site_name: Raptoreum Learn
site_url: https://explorer.raptoreum.com/tlp/

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    scheme: slate
    primary: black # LÃ¤sst den Header dunkel
    accent: orange
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - search.suggest
    - content.code.copy

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets

nav:
  - Learn:
      - Introduction: learn/intro.md
      - Tokenomics: learn/tokenomics.md
      - Glossary: learn/glossary.md
  - Getting Started:
      - Beginner's Guide: start/beginners.md
      - Exchanges: start/exchanges.md
      - Wallet Selection: start/wallets.md
  - Handbook:
      - Mining: handbook/mining.md
      - Core Wallet (Advanced): handbook/core-advanced.md
  - Smartnodes:
        - Overview: handbook/smartnodes/index.md
        - Setup Guide: handbook/smartnodes/setup.md    
  - Developer:
      - RPC Reference:
          - Overview: dev/rpc/index.md
          - Address Index: dev/rpc/addressindex.md
          - Assets: dev/rpc/assets.md
          - Blockchain: dev/rpc/blockchain.md
          - Control: dev/rpc/control.md
          - Evo: dev/rpc/evo.md
          - Generating: dev/rpc/generating.md
          - Mining: dev/rpc/mining.md
          - Network: dev/rpc/network.md
          - Raptoreum: dev/rpc/raptoreum.md
          - Raw Transactions: dev/rpc/rawtransactions.md
          - Util: dev/rpc/util.md
          - Wallet: dev/rpc/wallet.md
          - Zmq: dev/rpc/zmq.md
      - Knowless:
          - Transactions: dev/knowless/transactions.md
      - Bridges: dev/bridges.md
  - The Vault:
      - Whitepapers: vault/papers.md