site_name: Raptoreum Learn
site_url: https://explorer.raptoreum.com/tlp/

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    scheme: slate
    primary: black
    accent: orange
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - search.suggest
    - content.code.copy

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets

nav:
  - Wallets:
        - Raptoreum Core Wallet: 
            - Overview: handbook/wallets/core/index.md
            - Installation: handbook/wallets/core/installation.md
            - Bootstraps: handbook/wallets/core/bootstraps.md
            - HD Mode: handbook/wallets/core/hd_mode.md  
            - QT Wallet (Desktop):
              - Raptoreum Core QT: handbook/wallets/core/qt.md
              - Asstes:
                - Overview: handbook/wallets/core/assets/index.md
                - Video Tutorial: handbook/wallets/core/assets/tutorials.md
                - Quick Guide: handbook/wallets/core/assets/guide.md
            - CLI Wallet (Command Line):
              - Raptoreum Core CLI: handbook/wallets/core/cli/cli.md
              - Config & Start: handbook/wallets/core/cli/start.md
        - Stacy & Rapthorus:
            - Overview: handbook/wallets/webwallets/index.md
            - Rapthorus: handbook/wallets/webwallets/rapthorus/index.md
  - Mining:
        - Overview: handbook/mining/index.md
        - Raptorwings: handbook/mining/raptorwings.md
  - Smartnodes:
        - Overview: handbook/smartnodes/index.md
        - Knowless: handbook/smartnodes/knowless_smartnodes.md   
        - Setup Guide: handbook/smartnodes/setup.md
        - Troubleshooting: handbook/smartnodes/troubleshooting.md
  - Assets:
        - Overview: handbook/assets/index.md
        - Create on QT Wallet:
            - Video Tutorial: handbook/wallets/core/assets/tutorials.md
            - Quick Guide: handbook/wallets/core/assets/guide.md
  - Papers:
        - Overview: handbook/papers/index.md
        - Raptoreum Litepaper: handbook/papers/litepaper.md
        - Raptoreum Reward System: handbook/papers/reward_system.md
        - Ghostwriter Paper: handbook/papers/ghostwriter.md
  - Bridges:
        - BSC <-> RTM: handbook/bridges/bsc_rtm.md
  - Developer:
      - RPC Reference:
          - Overview: dev/rpc/index.md
          - Address Index: dev/rpc/addressindex.md
          - Assets: dev/rpc/assets.md
          - Blockchain: dev/rpc/blockchain.md
          - Control: dev/rpc/control.md
          - Evo: dev/rpc/evo.md
          - Generating: dev/rpc/generating.md
          - Mining: dev/rpc/mining.md
          - Network: dev/rpc/network.md
          - Raptoreum: dev/rpc/raptoreum.md
          - Raw Transactions: dev/rpc/rawtransactions.md
          - Util: dev/rpc/util.md
          - Wallet: dev/rpc/wallet.md
          - Zmq: dev/rpc/zmq.md
      - Transactions:
          - Overview: dev/knowless/transactions.md
          - Create Raw Transaction: dev/knowless/rawtransaction.md
      - IFPS Cluster:
          - Join The IPFS Cluster: dev/ipfs/index.md    